name: Build Nebula

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest version
        run: |
          NEBULA_VERSION=$(curl -fsSI https://github.com/slackhq/nebula/releases/latest | sed -n '/tag/s/.*\/v\(.*\)/\1/p' | tr -d \\r | tr -d \\n)
          curl -fsSL https://hub.docker.com/v2/repositories/gera2ld/nebula/tags/$NEBULA_VERSION && echo "$NEBULA_VERSION already exists" && exit 1 || true
          echo "NEBULA_VERSION=$NEBULA_VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build gera2ld/nebula
        uses: docker/build-push-action@v3
        with:
          file: ./nebula.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gera2ld/nebula:latest,gera2ld/nebula:${{env.NEBULA_VERSION}}
