name: Build Nebula

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - .vim/**
      - .gitignore
      - README.md

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build gera2ld/nebula
        uses: docker/build-push-action@v3
        with:
          file: ./nebula.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gera2ld/nebula:latest
