name: Build Easy

on:
  workflow_run:
    workflows: [Build Nebula]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_dispatch || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build gera2ld/nebula-easy
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: gera2ld/nebula-easy:latest
